### ISSUE TITLE
Thunk exceptions are being masked

### ISSUE THREAD

**Issue by jason-whitted** [reduxkotlin/redux-kotlin-thunk#14]
In [Thunk.kt](https://github.com/reduxkotlin/redux-kotlin-thunk/blob/master/lib/src/commonMain/kotlin/org/reduxkotlin/Thunk.kt) there is this try catch:
```kotlin
try {
	(action as Thunk<*>)(store.dispatch, store.getState, extraArgument)
} catch (e: Exception) {
	throw IllegalArgumentException()
// Logger.d("Dispatching functions must use type Thunk: " + e.message)
}
```

The try..catch is masking any errors that may have occurred in the thunk.
It would be helpful if it did something like this:
```kotlin
val thunk = try { action as Thunk<*> } 
            catch(ex: ClassCastException) { throw IllegalArgumentException() }
return thunk(store.dispatch, store.getState, extraArgument)
```

**Comment by patjackson52** [comment]
Thanks for reporting @jason-whitted issue has been fixed and will be published in the next release.
