### ISSUE TITLE
Cannot resolve dependency redux-kotlin-jvm-thunk:0.5.3

### ISSUE THREAD

**Issue by Baktiyar2018** [reduxkotlin/redux-kotlin-thunk#25]
ext.kotlin_version = "1.4.21".  Did't sync get output Failed to resolve: org.reduxkotlin:redux-kotlin-jvm-thunk:0.5.3

**Comment by mpetuska** [comment]
Gradle coordinates are incorrect. Should be `redux-kotlin-thunk-jvm:0.5.3`
