### ISSUE TITLE
Function detecton is not working on Kotlin/JS

### ISSUE THREAD

**Issue by rjaros** [reduxkotlin/redux-kotlin-thunk#5]
This condition is not working when running on Kotlin/JS.
```
if (action is Function<*>) {
```
It returns false when dispatched action is a lambda (transpilled to JS function).

**Comment by patjackson52** [comment]
I have opened an issue in kotlin tracker (Although it does need a reproducer) https://youtrack.jetbrains.com/issue/KT-33149

This has been updated to us a Thunk interface as a workaround.  Working in the latest release (0.2.8).
